{
 "title": "new-words.ru",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Rooms count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rooms_count" }
   ]
  },
  {
   "title": "Players count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "players_count" }
   ]
  },
  {
   "title": "API Graph",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "API" }
   ]
  },
  {
   "title": "Multiplayer Hits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Multiplayer" }
   ]
  }
 ]
}